<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <None Update="static\search.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\index.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\satisfactory.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="settings.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
